"""add tags column to RecommendedApp

Revision ID: 69761b1b5e9a
Revises: 2adcbe1f5dfb
Create Date: 2025-05-27 16:47:31.679402

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69761b1b5e9a'
down_revision = '2adcbe1f5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=False))

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('exceptions_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_steps',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('recommended_apps', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
